---
name: Create and publish a container

on:
  push:
    branches:
      - main

  workflow_dispatch: {}

env:
  GH_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Extract version from Dockerfile
        id: extract_version
        run: |
          VERSION=$(grep 'FROM alpine' Dockerfile | cut -d ':' -f2)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Upsert git tag
        run: |
          TAG="v${{ env.VERSION }}"
          # Check if tag already exists
          if git rev-parse "$TAG" >/dev/null 2>&1; then
            echo "Tag $TAG already exists. Skipping creation."
          else
            git tag "$TAG"
            git push origin "$TAG"
            echo "Tag $TAG created and pushed."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to registry
        uses: docker/login-action@v3.2.0
        with:           
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Extract metadata for container
        id: gcr
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ env.GH_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ env.VERSION }}
            type=ref,event=branch

      - name: Build and push container image
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: ${{ steps.gcr.outputs.tags }}
          labels: ${{ steps.gcr.outputs.labels }}
